/** "ogsus" */

#ifndef _HEAVY_CONTEXT_SIMPLE_OSC_HPP_
#define _HEAVY_CONTEXT_SIMPLE_OSC_HPP_

// object includes
#include "HeavyContext.hpp"
#include "HvControlVar.h"
#include "HvSignalBiquad.h"
#include "HvSignalRPole.h"
#include "HvSignalTabwrite.h"
#include "HvTable.h"
#include "HvControlIf.h"
#include "HvSignalTabread.h"
#include "HvControlUnop.h"
#include "HvControlTabhead.h"
#include "HvControlPack.h"
#include "HvMath.h"
#include "HvControlDelay.h"
#include "HvControlSystem.h"
#include "HvSignalDel1.h"
#include "HvControlCast.h"
#include "HvControlSlice.h"
#include "HvSignalLine.h"
#include "HvSignalPhasor.h"
#include "HvControlBinop.h"
#include "HvSignalVar.h"

class Heavy_Simple_OSC : public HeavyContext {

 public:
  Heavy_Simple_OSC(double sampleRate, int poolKb=10, int inQueueKb=2, int outQueueKb=0);
  ~Heavy_Simple_OSC();

  const char *getName() override { return "Simple_OSC"; }
  int getNumInputChannels() override { return 0; }
  int getNumOutputChannels() override { return 2; }

  int process(float **inputBuffers, float **outputBuffer, int n) override;
  int processInline(float *inputBuffers, float *outputBuffer, int n) override;
  int processInlineInterleaved(float *inputBuffers, float *outputBuffer, int n) override;

  int getParameterInfo(int index, HvParameterInfo *info) override;
  struct Parameter {
    struct In {
      enum ParameterIn : hv_uint32_t {
        PITCH = 0x94DB5AB5, // Pitch
        REVFEEDBACK = 0xB3A0D463, // RevFeedback
        REVGAIN = 0x3B2EB6DE, // RevGain
        REVPREDELAY = 0x30ADF4D0, // RevPredelay
        VOLUME = 0x528845DB, // Volume
      };
    };
  };

 private:
  HvTable *getTableForHash(hv_uint32_t tableHash) override;
  void scheduleMessageForReceiver(hv_uint32_t receiverHash, HvMessage *m) override;

  // static sendMessage functions
  static void cBinop_eKCsiUr7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_AaOVdxNF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_uDpDNbB4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_LE3gqBY6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rARrkwIJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ADPLGdTq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_oEasL5Ja_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_8h6yv4P2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_B07GtfhF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_YyNjTChe_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_8z8gRWq4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_E6yr6AH1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_fzktp6hB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_dqgzl3eC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Dwd1z80e_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_Er0xfhmM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_n1tkoY1f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_ztGtgrId_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8meShVPo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lo3TMpRu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_VhO8I8s9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Lhir3N6H_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_RJoB3Eyp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_DRKC452Z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_sPvJIiFq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_WVEAZUSk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Si0GbZ9x_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lMLMURNf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_0jaaQKO1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nGltOyeh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_GPo35xHu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_IWr9SyFx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_ueiHfVuw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_p9oHtABw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_m0mgHAfO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6F2g8Uqx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_zzJyIoC8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_aTLwq1h8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_YRiMEQb0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_bUYtybq9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_dE8suCN1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_zV5HFpAZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_PmmaTQjw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_dAGEuLo9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_m9kMF57f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_URTglQTu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JYSXFGqf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Pa69xiza_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_9DMRrgee_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lh3R8dLh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_uCht4qTZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ifwkCXeD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_GYOkUPrz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_N4B79IaQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_0YOVWqdZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_IQZVpVop_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_TYBi9WxK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_gvj1VlK3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_srLu67E4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_I7RIlFNI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_jnpfFGdg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xylzSMQf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_JvdejEno_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Bc0OJ6Bg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Z5XUUXFP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_GWa74Sti_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_giWAIegS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dPcYEAI9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5ArJFYO7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_fzHY6BAg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_TwWanXSk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_XbMrlZqy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_8jLe2JDL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_v3ARyak1_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_wZKltFVK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_UdFPOQ49_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_E1fn8LZF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_Bx6erMo2_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_U9h2ZTnK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_BIB35HvI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_HCDWzK2c_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_5e2Z2jR4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_Bzyu5tsQ_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_4YquwDBg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_TNq6hnAL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ULPqfpwp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_evBNgiA4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_PSdCwsZk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_3cbUEHYh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_wEJr0Lfx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_KmFshei8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_rxD5DaUK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rHWImn1H_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mPYoTuHE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_49sdgOhh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_GQTa17sO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_Btq7hu3A_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Cv9zQmsi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Jzm9Ct8S_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_bPz6kkSB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_epjLT3x7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lSSrhr9B_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_BZM39Jom_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_4HK7mG0r_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_HaSa0RAY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_MOSCfNb9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_6FRH3mLL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_dBjKk424_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_JB2JezBQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_F6he36cG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_VaPAHRWf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Zuja3eqB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gUiLHgou_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0Kh2vnx6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_eRZ9dW8a_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BlLwV6UK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_wqzBfZHN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Uds1MRbL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_VxF2zgu4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_IDSJglh1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_MZw5LOPt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_LeH1jsBr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_YuZNJVbU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_nlfuXDYX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_tHT9ZdON_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_grNFbZ2Z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_PgDi8ujy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_XArqJqPL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gsKNNO9K_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_vZ7f1Unq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tBZNrSA1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_WtrJuht6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_jPp4B3hq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_YwjsVlHl_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_piREEXfM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_klLqmccc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jWMw4bL2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_z6LYiF88_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_jDYXEuBl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Yb90o7xS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_AEbvrwto_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_3zAKiIjb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_Uwh5AVN9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_zf5kwmJd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_6jgSdoQH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_bvo10OOf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_RK1XnSM0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_mAvKkT9M_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_nk5fKQwl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_JZ3NtcjK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_2ZnKPYmP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6cj1YaIN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7fgPGlw4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JKrKPPmK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_49rLKMmR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xjInRJDF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_d8wYonzR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_op6cEFFt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_e5OPHExn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_wy4RGlw4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_xYWBjXCw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_4AqZDi7l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_vjGOvqle_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_UWHj8ayx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_E2wYnWKU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_PxEx7qk4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_GRZbCZvT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_8XZc3BCp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_K0soYUoj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_h6wtiH2o_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TfKjqDTv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_F8mhnH3I_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_5zZpde5V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_GMQC4IDy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_SIzgVoZ3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_XVJJXriT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Am0U3gWm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_QREXhBQm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_vhb9rSMr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_tYXmCCTe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_qFvvP5pf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_RnwccXgx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_wkItuzTo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_XeOUAD5C_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_UZChYgFm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_fcLBZEXr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jd60GAvZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ApKuPKDC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nDw0Dh1P_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5Y6ICDCA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_R0pAnWOw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_jumdkhGM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_6RnyyNSK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_IzKHB5W0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_swwECBwQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2Yil7wAm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_y8DDF5yl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_0oTQrFFl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_FVmfymBt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_XwyxhgDT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_dUOODXZT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_x9o4pJvt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_h4Pg40he_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_FEYUtYor_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_5Uboqmcb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_4edZbj61_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WFVWroUa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0L5Wy1DX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4GdfSq22_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Ncb6gmEI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_osisMLuu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5VnkM7nt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_8iE2UIBC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_kLha7l8L_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_HizvAmfK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_q0juPKiY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8iVWnzYI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_EZQExJry_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_ngvGUf8e_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_zXhSR4g1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_FDoyWIR9_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_kWm66dYO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_NKdZeIZq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_fJdu8tvC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Jtvsj1mx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_UhyIfFis_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_F5vY5TAX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_o7Url4We_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_fMnB5UyA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_wFRpwm2z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_h9dI1JgL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jWciKnLI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_cH3V9RMD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_SSZnlTAH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ouB5ANXH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7kriR7zK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KnyTm6g4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_8gVF1C68_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_8FUA5Xe7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_UEjZjIAu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rMiAwq3o_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Zs4a2ISH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_mPAsV89r_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6wX0Dp1u_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_O1NzmziO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_jvK3ko3w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_mN8JVovJ_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_toTiKfI3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_2SbBPx4t_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_SsW908vR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Zyxauq02_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hjWzye89_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_qjB2r8be_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_dW9LdpUF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_APzmmhvm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_3UDQtrHM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_WkVEWO1w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_Nl0G9A5d_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_IXUE6fSI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_QqK6hYHG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_LGV0iaVb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_xiCwA0LD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_8Vu9djT9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_3k55mbxt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Lsp5clF5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_HWi0rKDh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6mNmEFw8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_DyNaCzgk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5kJwiom6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nYOC3ynU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_KOJcedGA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_pYsjcnKJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_V9xLRaDE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_fhtHopK4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rbnznitF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_YYyDnc8a_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_oqogXi1v_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_mHZTAJUz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_1TbZ56zJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_Jt21PN6Z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_IGbA7P7Z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hqmxlBri_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_waYbKRIH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8oQEoV6m_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BqeU1pvt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5OMDVqAG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MelwPF7y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WJpOgHlr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ritbmqVn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_QgjYG6Ar_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_f1RKgtN2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_lFk53U4d_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_wEJwCndH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xNfDLMIz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_1W5Zn4Hv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_9FhLHeY4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_MwPJCO4Y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_jHQIgz90_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_ZWTKdWi3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_j5ORhi5Y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_bKAXYVix_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4giJ4XHv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_1WI2bH6r_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_41nhMyf6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_zSmSPbfu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_WpCC10vD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_IeYC6xiw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_3UufUVep_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_AxFTG7ad_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_A1gXXDxD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_d0N7iqor_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_oQLHbe5R_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_gaY8Hcd0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_brRdrWEf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_aBR8lIAs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_w1hk8AFC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_KDcjO8fI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_1sYZsMCs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_n8aiKreT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_8UAmViBd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_AaxEAj9G_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_eVDzPd6y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_jeG82HcH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_pvQxq8h6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_gSHVY637_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_fQuCmKY8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_YtS1PwHX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_OWVPm1wn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_AojlsIgp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_j9nhDTiv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_i2UdtvFn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zxfQ0uNO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0UQtIrEC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Jg2yFvQw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_0d8tLvzO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_cT99NwAT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Z66wymyG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_Avi8Fd5I_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_FU58g30S_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_I0fOadrS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_cd7TI9vl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_4kRRnywY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_zgkx73vz_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_Av35co2F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_zWMgzbBz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zVJD4TWG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3EfRYXxy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_YCVEZ6u4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_sBzREwuo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_E8CLcReu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_cnLpf2ri_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_r7ICE3O6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_FPx8ked6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_oXDpM5PW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_r6Re24fP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_dIAN6gNl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_zVnfbG9O_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_q0jLN3Li_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Id6xE7x6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_V1TRTbHn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_1NW6Kx6n_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7Tg9hFTm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CMkk36X9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WMdp1kR9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5kPQdasK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_B7RdC88l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hlQx3pgg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_YudCaEzQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_y5lPENlH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_xDhsp7HB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_zgeqXTij_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_G9plVJJW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_jqFl75bD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_wx9UF834_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_kmtRu0Ub_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_yBJrUUUD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_EEkLlmQd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_K7DTBWnA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_eapxwLKa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_iA5jp0rs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZyqiOv8V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lubZcU26_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_DVoul22Y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JEy84GDr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6J1HVHBk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_kPXTHLzn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_REUDX8UV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_nMk4RniC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_P5JclrqL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_i71ui3rN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Dh9XHVD6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_haUl0INL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_7xhQg2qf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_pydcmh5W_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_DkWGpMRt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_8YiMXznz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gY1VNTxi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_hls827Jk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_61XS9CgO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_1hqqB0sI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_VFaa7MPf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_SWwjgoSD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_dYnlmTK9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_QC5aUoxp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_aQwSz9Rm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_jn7zJYf4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_5pWKcwlx_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_jBiHsz1Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_7RE6sAK5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_cAjYXhgn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kwI2n0W4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_z8HxV3gz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_1DRdSEse_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Nj3wfHtQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_mpTQGjpB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_fqwvMdHt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Cnu9eMik_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_HyXHIJIQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_8j0SujJF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_mFlqjEBU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_jhXBb0XU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_P3KGirJP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_syaYWKCY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_KZAZpLZK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_D6w3e4wk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JarDctxs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_OS8M39nX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0c0L7v8U_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_yEr5Ecnc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zOeWczwu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_IVfzWEoJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hoP28gq2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_WXxsYHpk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_51JvOl64_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_QybDfZDH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_oF85CDsV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0ex6Ff40_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_FHASIirA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_FVAkFKnh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_NSjnahGI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_PtZp7lAE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_IHoLVV3u_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ls5i0Gsf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_UapMPoOs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lXNNSEKQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_pzBLz1pJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_Gcsw9qiH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_aTQmzDze_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_JbGtmHc5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_5VehfVHu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_pKOy4Oyw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QB7S0K9z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_NKnoxSpe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_JEDW8dI5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_r6DfyKsG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Iu8HCIjR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_vEzHUOio_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ljXv9wmq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cPack_slLyXUuy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cPack_5W3ZowqF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cPack_DmMYPr42_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_D1pBEVed_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8y1zuEOK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_qGZqdUHb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ohMTtY40_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_6Sb85ZpO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_u6tKN3w5_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_bDu43SBt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_Ju0zlNTh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_5YLtxTFn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_BdHlDum9_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_RMbPYmR4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_5KrfTwmI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_IuzEIXPu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WYQAZsOE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3XHBsX5v_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_V4D0TSNQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jC1kJxsR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_DOoa9Zfw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_yvjY0Ast_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_f4NRB6jm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_iyKAvG8D_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_6bEtRjxN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_nhmUpZez_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_v6IxFK1a_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hOnXan3F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XWd42ll8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_aKDl9DSS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_XQx2E3uf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_T7SdytLE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MAi41w54_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_mkH8Ybpt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5kk39Woz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_cHkEmAWH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_vZw2eYN4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_NVJTxuzP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_356bA4V6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_9REJW0QA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_gkqOEViu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Ww3SqZ8O_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_BSvR2BHX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_JdcVsBUW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_78oQy0ip_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3OVxoZ31_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_A59DkC8B_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_9HLAElQQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_tQOuOkcP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_2HgrfoHE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KY3t4PWh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_1lvgyABC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lV7qaoyx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_nm5uzEMY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_b0n3SFOz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_9UFU7jMB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_EsmNcGSm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TzOTEQhL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_b45xc2ho_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_2V8JLgRt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_bJLltkZy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_IiGtBJOs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WG7vbwGV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_f6tzCFiq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_YizSwjVV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_3PctkjFk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_iP3GlmLG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_QFe8j4Vi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_LsLWuoCT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dxfNduC1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2vwJGNQk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Lh0N8qtP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_21innQH3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_4nwUP6gf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ran7tYzU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_1vokAHVr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_9Rre90uq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Jy3x5gub_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_atcmiqBg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xwVnm15i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_G3ZwVd2H_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_iy96iLmJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_YmGPTg0J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_k8uKx4Do_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_mfUaSQsn_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_EtxduE5p_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_IuwbHICL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_TO3oudhq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_AItO66D4_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_UNEdgFgt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_3Qxzv7lc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_CfZQ1jW9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_4ANv9fTU_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_39SVSkWK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_ndPld8Og_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_QI0tfG6e_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_x5jxqdf0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_skFXrjYZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_W40vjxgb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8Jmp4C83_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_xxxw3dBc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_ypPUX6j5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_KoBxyLN5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_til7LQfc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_N5dSmzzJ_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_UEW85Amf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_2Sny5fiP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XT6DHUsp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CSYHZEk5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Vzxfray2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_mBcxaUKO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_nj2WJPzX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_OfhzkcbI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_SeBwXseX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Wy5pgs7X_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cPack_KRLz9hP2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_HIk0jG4X_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_eODiAkxk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_UnXpk3hI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_nZuk2nbE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_mvSzT3rH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Abp6iKPP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_HTnyWwxS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_i3T4hqzB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZGMplFY2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_KYKE5EYX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_R6dqWvhe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_HAfEQg8P_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_jkAWBrIz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_TEnCZc49_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_8ADOEemw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_cKPxUPYc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_YmbwKKz0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_C4SUUbdD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zyulCZP2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jEicegz4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_XTTwoBk4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_irIbye03_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ylQFSHYR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GanTOILO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_CH7aQuSS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_AzSrXSrq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_VuMsrcA5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_g0EtWsUH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0DG6rk5y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_NWxSBeQq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_bEnZlfzy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_vQFkBTuk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_NYD5Tt1S_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0c4OgTVH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KQlp34Qe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_HoPOFgk0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_YyAoYgTN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_iFRPIAD1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rTmjrMtV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rRAD2XRm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_vi4NvLOA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_he8GwGPJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_yARal7qO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Ksi0TZGi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_koB6qCM9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_BBRiJlDh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_orQA3PTi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_aZqkYtcX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_LsdQjw11_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_FPfgLPoX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_WrVtCBd8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_vnL73Lmr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_uuCBpWWL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kpY0nmTq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_FLtEsITu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_GxHG7mkX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_BcyBwfww_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_uWiRd3vN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_GawDe2vM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5o8fXOpe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_W469hhh8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_pT3QNNDM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_BBP5qm9p_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ZZeKFh3n_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_5ID8RKb2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ZmixOlin_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Tau8vPdr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_72Lxq37S_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_DmbGhClQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_zio3wnJy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7KJg7Hov_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_gWQI1JZG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_6ft77wPK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_QVSg9Vd1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_XG0qb4u1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_pDnLTR0C_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_K1FLPi3P_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_isIzhI8V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_v2jJclJJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_NHwJKGKN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_46oQit7t_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_J9cYiiZm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_y8jGYTkk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_17ygIKGr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_9cf89EFf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_1qrTbuoK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_8qSfNDmc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_qdZw2Osg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_JoEPzwFW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_iQFc2S9u_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_56ZRPYf1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Yk7kiyB1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_y4ufv4b7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_SpsCvwvX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_wJY25jrG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_vKsJKA7B_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_3J5NbtG3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_OCkUz74R_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_2JN0pZ6s_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_aaK7Eoxq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_TBhT7TI1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_Xw2KIgtN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_B8VHCqVX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_H2cPiLhW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_r8ysJu0a_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_vgmTGzZc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_4Jk88MkG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_xerl4fV7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_YqVgIFI7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_IdFojawY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_YJcJuuEq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_LauuFJcm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_JfdBhlWd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_ZvYzhgQD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_vqW9nFnF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_KNmnjTra_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_iRbXNruw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_GX3tE4cE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_ZcOkaWFv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_GEVtzi19_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_wMY0TQAO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_9Wg9MfEm_sendMessage(HeavyContextInterface *, int, const HvMessage *);

  // objects
  SignalLine sLine_FtgFn97w;
  SignalLine sLine_FLyjoGIr;
  SignalLine sLine_EhUdLVFO;
  SignalLine sLine_lix26rKm;
  SignalLine sLine_6V0y3mVw;
  SignalBiquad sBiquad_s_LyumCObU;
  SignalPhasor sPhasor_bh9mGeDs;
  SignalTabwrite sTabwrite_jSRaB2R0;
  SignalTabhead sTabhead_H3ZrOu5I;
  SignalTabread sTabread_vwd3ZzYl;
  SignalTabread sTabread_9kWI82GW;
  SignalLine sLine_RRuOK4Wp;
  SignalLine sLine_eVIh8VCN;
  SignalLine sLine_EARCrUps;
  SignalLine sLine_p8rICfby;
  SignalLine sLine_h9oFFBlW;
  SignalBiquad sBiquad_s_GsAKPzzW;
  SignalLine sLine_cb9wJ458;
  SignalLine sLine_DSg3PVBf;
  SignalLine sLine_seZM77CZ;
  SignalLine sLine_JGpbZh7Z;
  SignalLine sLine_JG0LoJNn;
  SignalBiquad sBiquad_s_lZxdP3pe;
  SignalTabread sTabread_h4Pg40he;
  SignalRPole sRPole_Zq8HpVpq;
  SignalLine sLine_B4h7ZNna;
  SignalLine sLine_lj6SxHyl;
  SignalTabread sTabread_LGV0iaVb;
  SignalTabread sTabread_zVnfbG9O;
  SignalTabwrite sTabwrite_hdNBKFO9;
  SignalTabwrite sTabwrite_ELhT3A9C;
  SignalTabwrite sTabwrite_ULxPSvNG;
  SignalTabread sTabread_Jt21PN6Z;
  SignalTabread sTabread_jhXBb0XU;
  SignalTabwrite sTabwrite_zpcjGJt8;
  SignalTabwrite sTabwrite_KdsQKYlT;
  SignalTabread sTabread_gSHVY637;
  SignalTabwrite sTabwrite_VKXFTFym;
  SignalTabread sTabread_yBJrUUUD;
  SignalTabread sTabread_mAvKkT9M;
  SignalRPole sRPole_yvGALiLj;
  SignalTabread sTabread_qFvvP5pf;
  SignalRPole sRPole_yfk5Orgq;
  SignalTabread sTabread_6FRH3mLL;
  SignalRPole sRPole_qV8YGfWl;
  SignalTabwrite sTabwrite_mEBF4H9c;
  SignalTabwrite sTabwrite_lK4PO21M;
  SignalTabwrite sTabwrite_hAcsQgoN;
  SignalTabwrite sTabwrite_eNxRpEDE;
  SignalLine sLine_4p6cdlhP;
  SignalLine sLine_tBCmODUp;
  ControlBinop cBinop_eKCsiUr7;
  ControlBinop cBinop_AaOVdxNF;
  ControlBinop cBinop_uDpDNbB4;
  ControlBinop cBinop_rARrkwIJ;
  SignalVarf sVarf_AhX1HHYl;
  ControlVar cVar_ADPLGdTq;
  ControlVar cVar_oEasL5Ja;
  ControlVar cVar_8h6yv4P2;
  ControlVar cVar_B07GtfhF;
  ControlSlice cSlice_8z8gRWq4;
  ControlBinop cBinop_Dwd1z80e;
  ControlBinop cBinop_8meShVPo;
  ControlBinop cBinop_lo3TMpRu;
  ControlBinop cBinop_VhO8I8s9;
  ControlBinop cBinop_DRKC452Z;
  ControlBinop cBinop_sPvJIiFq;
  ControlBinop cBinop_Si0GbZ9x;
  ControlBinop cBinop_lMLMURNf;
  ControlVar cVar_0jaaQKO1;
  ControlBinop cBinop_nGltOyeh;
  ControlVar cVar_p9oHtABw;
  ControlBinop cBinop_m0mgHAfO;
  ControlBinop cBinop_6F2g8Uqx;
  ControlBinop cBinop_aTLwq1h8;
  ControlBinop cBinop_YRiMEQb0;
  ControlBinop cBinop_bUYtybq9;
  ControlBinop cBinop_dE8suCN1;
  ControlVar cVar_PmmaTQjw;
  ControlBinop cBinop_dAGEuLo9;
  ControlBinop cBinop_m9kMF57f;
  ControlBinop cBinop_URTglQTu;
  ControlBinop cBinop_JYSXFGqf;
  ControlBinop cBinop_Pa69xiza;
  ControlBinop cBinop_9DMRrgee;
  ControlBinop cBinop_lh3R8dLh;
  ControlBinop cBinop_uCht4qTZ;
  ControlBinop cBinop_ifwkCXeD;
  ControlVar cVar_8jLe2JDL;
  ControlSlice cSlice_wZKltFVK;
  ControlVar cVar_E1fn8LZF;
  ControlSlice cSlice_U9h2ZTnK;
  ControlDelay cDelay_HCDWzK2c;
  ControlDelay cDelay_5e2Z2jR4;
  ControlBinop cBinop_ULPqfpwp;
  ControlBinop cBinop_evBNgiA4;
  HvTable hTable_rxD5DaUK;
  ControlBinop cBinop_mPYoTuHE;
  ControlBinop cBinop_49sdgOhh;
  SignalVarf sVarf_LYiVvt4o;
  ControlBinop cBinop_Cv9zQmsi;
  ControlBinop cBinop_Jzm9Ct8S;
  ControlVar cVar_epjLT3x7;
  ControlBinop cBinop_lSSrhr9B;
  SignalVarf sVarf_zMNOitM2;
  ControlVar cVar_BZM39Jom;
  ControlDelay cDelay_4HK7mG0r;
  ControlDelay cDelay_HaSa0RAY;
  ControlTabhead cTabhead_MOSCfNb9;
  ControlVar cVar_dBjKk424;
  ControlBinop cBinop_VaPAHRWf;
  ControlBinop cBinop_Zuja3eqB;
  ControlBinop cBinop_gUiLHgou;
  ControlBinop cBinop_0Kh2vnx6;
  ControlBinop cBinop_eRZ9dW8a;
  ControlBinop cBinop_BlLwV6UK;
  SignalVarf sVarf_YlKN4pbS;
  ControlVar cVar_YuZNJVbU;
  ControlBinop cBinop_grNFbZ2Z;
  ControlBinop cBinop_PgDi8ujy;
  ControlBinop cBinop_gsKNNO9K;
  ControlBinop cBinop_vZ7f1Unq;
  ControlBinop cBinop_tBZNrSA1;
  SignalVarf sVarf_qIy6Qj3U;
  ControlDelay cDelay_WtrJuht6;
  ControlDelay cDelay_jPp4B3hq;
  ControlBinop cBinop_jWMw4bL2;
  ControlBinop cBinop_z6LYiF88;
  HvTable hTable_Uwh5AVN9;
  ControlDelay cDelay_6jgSdoQH;
  ControlDelay cDelay_bvo10OOf;
  ControlTabhead cTabhead_RK1XnSM0;
  ControlVar cVar_nk5fKQwl;
  ControlBinop cBinop_6cj1YaIN;
  ControlBinop cBinop_7fgPGlw4;
  ControlBinop cBinop_JKrKPPmK;
  ControlBinop cBinop_49rLKMmR;
  ControlBinop cBinop_xjInRJDF;
  ControlBinop cBinop_d8wYonzR;
  ControlIf cIf_UWHj8ayx;
  ControlBinop cBinop_E2wYnWKU;
  ControlVar cVar_PxEx7qk4;
  ControlVar cVar_GRZbCZvT;
  ControlIf cIf_8XZc3BCp;
  ControlBinop cBinop_K0soYUoj;
  ControlBinop cBinop_h6wtiH2o;
  ControlBinop cBinop_TfKjqDTv;
  ControlBinop cBinop_F8mhnH3I;
  ControlBinop cBinop_SIzgVoZ3;
  ControlDelay cDelay_QREXhBQm;
  ControlDelay cDelay_vhb9rSMr;
  ControlTabhead cTabhead_tYXmCCTe;
  ControlVar cVar_RnwccXgx;
  ControlBinop cBinop_UZChYgFm;
  ControlBinop cBinop_fcLBZEXr;
  ControlBinop cBinop_jd60GAvZ;
  ControlBinop cBinop_ApKuPKDC;
  ControlBinop cBinop_nDw0Dh1P;
  ControlBinop cBinop_5Y6ICDCA;
  ControlVar cVar_y8DDF5yl;
  ControlVar cVar_0oTQrFFl;
  ControlVar cVar_FVmfymBt;
  ControlDelay cDelay_XwyxhgDT;
  ControlDelay cDelay_dUOODXZT;
  ControlTabhead cTabhead_x9o4pJvt;
  ControlVar cVar_FEYUtYor;
  ControlBinop cBinop_WFVWroUa;
  ControlBinop cBinop_0L5Wy1DX;
  ControlBinop cBinop_4GdfSq22;
  ControlBinop cBinop_Ncb6gmEI;
  ControlBinop cBinop_osisMLuu;
  ControlBinop cBinop_5VnkM7nt;
  ControlDelay cDelay_ngvGUf8e;
  ControlDelay cDelay_zXhSR4g1;
  ControlBinop cBinop_fJdu8tvC;
  ControlBinop cBinop_Jtvsj1mx;
  HvTable hTable_wFRpwm2z;
  ControlBinop cBinop_jWciKnLI;
  ControlBinop cBinop_cH3V9RMD;
  ControlBinop cBinop_SSZnlTAH;
  ControlBinop cBinop_ouB5ANXH;
  ControlBinop cBinop_7kriR7zK;
  ControlBinop cBinop_KnyTm6g4;
  ControlVar cVar_8gVF1C68;
  SignalVarf sVarf_GiQa4Ifp;
  ControlBinop cBinop_rMiAwq3o;
  ControlBinop cBinop_Zs4a2ISH;
  ControlBinop cBinop_6wX0Dp1u;
  SignalVarf sVarf_bhOSN2Hf;
  ControlDelay cDelay_O1NzmziO;
  ControlDelay cDelay_jvK3ko3w;
  ControlBinop cBinop_SsW908vR;
  ControlBinop cBinop_Zyxauq02;
  HvTable hTable_3UDQtrHM;
  ControlDelay cDelay_Nl0G9A5d;
  ControlDelay cDelay_IXUE6fSI;
  ControlTabhead cTabhead_QqK6hYHG;
  ControlVar cVar_xiCwA0LD;
  ControlBinop cBinop_Lsp5clF5;
  ControlBinop cBinop_HWi0rKDh;
  ControlBinop cBinop_6mNmEFw8;
  ControlBinop cBinop_DyNaCzgk;
  ControlBinop cBinop_5kJwiom6;
  ControlBinop cBinop_nYOC3ynU;
  ControlDelay cDelay_oqogXi1v;
  ControlDelay cDelay_mHZTAJUz;
  ControlTabhead cTabhead_1TbZ56zJ;
  ControlVar cVar_IGbA7P7Z;
  ControlBinop cBinop_8oQEoV6m;
  ControlBinop cBinop_BqeU1pvt;
  ControlBinop cBinop_5OMDVqAG;
  ControlBinop cBinop_MelwPF7y;
  ControlBinop cBinop_WJpOgHlr;
  ControlBinop cBinop_ritbmqVn;
  ControlDelay cDelay_9FhLHeY4;
  ControlDelay cDelay_MwPJCO4Y;
  ControlBinop cBinop_bKAXYVix;
  ControlBinop cBinop_4giJ4XHv;
  HvTable hTable_IeYC6xiw;
  ControlDelay cDelay_AxFTG7ad;
  ControlDelay cDelay_A1gXXDxD;
  ControlBinop cBinop_brRdrWEf;
  ControlBinop cBinop_aBR8lIAs;
  HvTable hTable_8UAmViBd;
  ControlDelay cDelay_eVDzPd6y;
  ControlDelay cDelay_jeG82HcH;
  ControlTabhead cTabhead_pvQxq8h6;
  ControlVar cVar_fQuCmKY8;
  ControlBinop cBinop_AojlsIgp;
  ControlBinop cBinop_j9nhDTiv;
  ControlBinop cBinop_i2UdtvFn;
  ControlBinop cBinop_zxfQ0uNO;
  ControlBinop cBinop_0UQtIrEC;
  ControlBinop cBinop_Jg2yFvQw;
  ControlDelay cDelay_cd7TI9vl;
  ControlDelay cDelay_4kRRnywY;
  ControlBinop cBinop_zVJD4TWG;
  ControlBinop cBinop_3EfRYXxy;
  HvTable hTable_r7ICE3O6;
  ControlDelay cDelay_oXDpM5PW;
  ControlDelay cDelay_r6Re24fP;
  ControlTabhead cTabhead_dIAN6gNl;
  ControlVar cVar_q0jLN3Li;
  ControlBinop cBinop_1NW6Kx6n;
  ControlBinop cBinop_7Tg9hFTm;
  ControlBinop cBinop_CMkk36X9;
  ControlBinop cBinop_WMdp1kR9;
  ControlBinop cBinop_5kPQdasK;
  ControlBinop cBinop_B7RdC88l;
  ControlDelay cDelay_jqFl75bD;
  ControlDelay cDelay_wx9UF834;
  ControlTabhead cTabhead_kmtRu0Ub;
  ControlVar cVar_EEkLlmQd;
  ControlBinop cBinop_iA5jp0rs;
  ControlBinop cBinop_ZyqiOv8V;
  ControlBinop cBinop_lubZcU26;
  ControlBinop cBinop_DVoul22Y;
  ControlBinop cBinop_JEy84GDr;
  ControlBinop cBinop_6J1HVHBk;
  ControlDelay cDelay_haUl0INL;
  ControlDelay cDelay_7xhQg2qf;
  ControlBinop cBinop_gY1VNTxi;
  ControlBinop cBinop_hls827Jk;
  HvTable hTable_dYnlmTK9;
  ControlDelay cDelay_aQwSz9Rm;
  ControlDelay cDelay_jn7zJYf4;
  ControlBinop cBinop_cAjYXhgn;
  ControlBinop cBinop_kwI2n0W4;
  HvTable hTable_fqwvMdHt;
  ControlDelay cDelay_HyXHIJIQ;
  ControlDelay cDelay_8j0SujJF;
  ControlTabhead cTabhead_mFlqjEBU;
  ControlVar cVar_P3KGirJP;
  ControlBinop cBinop_D6w3e4wk;
  ControlBinop cBinop_JarDctxs;
  ControlBinop cBinop_OS8M39nX;
  ControlBinop cBinop_0c0L7v8U;
  ControlBinop cBinop_yEr5Ecnc;
  ControlBinop cBinop_zOeWczwu;
  ControlBinop cBinop_0ex6Ff40;
  ControlBinop cBinop_FHASIirA;
  ControlBinop cBinop_PtZp7lAE;
  ControlBinop cBinop_IHoLVV3u;
  ControlVar cVar_UapMPoOs;
  SignalVarf sVarf_wVGDKJnj;
  ControlBinop cBinop_lXNNSEKQ;
  SignalVarf sVarf_8ITqtsN8;
  ControlDelay cDelay_pzBLz1pJ;
  ControlDelay cDelay_Gcsw9qiH;
  ControlBinop cBinop_pKOy4Oyw;
  ControlBinop cBinop_QB7S0K9z;
  HvTable hTable_vEzHUOio;
  ControlPack cPack_slLyXUuy;
  ControlPack cPack_5W3ZowqF;
  ControlPack cPack_DmMYPr42;
  ControlBinop cBinop_D1pBEVed;
  ControlBinop cBinop_8y1zuEOK;
  ControlBinop cBinop_qGZqdUHb;
  ControlVar cVar_6Sb85ZpO;
  ControlSlice cSlice_bDu43SBt;
  ControlVar cVar_5YLtxTFn;
  ControlSlice cSlice_RMbPYmR4;
  ControlIf cIf_IuzEIXPu;
  ControlBinop cBinop_WYQAZsOE;
  ControlBinop cBinop_3XHBsX5v;
  ControlBinop cBinop_V4D0TSNQ;
  ControlBinop cBinop_jC1kJxsR;
  ControlBinop cBinop_f4NRB6jm;
  ControlBinop cBinop_XWd42ll8;
  ControlBinop cBinop_aKDl9DSS;
  ControlVar cVar_XQx2E3uf;
  ControlBinop cBinop_T7SdytLE;
  ControlBinop cBinop_MAi41w54;
  ControlVar cVar_mkH8Ybpt;
  ControlBinop cBinop_5kk39Woz;
  ControlBinop cBinop_cHkEmAWH;
  ControlVar cVar_vZw2eYN4;
  ControlBinop cBinop_NVJTxuzP;
  ControlBinop cBinop_356bA4V6;
  ControlBinop cBinop_78oQy0ip;
  ControlBinop cBinop_3OVxoZ31;
  ControlBinop cBinop_A59DkC8B;
  ControlBinop cBinop_2HgrfoHE;
  ControlBinop cBinop_KY3t4PWh;
  ControlBinop cBinop_1lvgyABC;
  ControlBinop cBinop_lV7qaoyx;
  ControlBinop cBinop_b0n3SFOz;
  ControlBinop cBinop_9UFU7jMB;
  ControlBinop cBinop_EsmNcGSm;
  ControlBinop cBinop_TzOTEQhL;
  ControlBinop cBinop_b45xc2ho;
  ControlBinop cBinop_2V8JLgRt;
  ControlBinop cBinop_bJLltkZy;
  ControlBinop cBinop_IiGtBJOs;
  ControlBinop cBinop_WG7vbwGV;
  ControlBinop cBinop_f6tzCFiq;
  ControlVar cVar_k8uKx4Do;
  ControlSlice cSlice_EtxduE5p;
  ControlVar cVar_TO3oudhq;
  ControlSlice cSlice_UNEdgFgt;
  SignalVarf sVarf_SLeohyot;
  ControlVar cVar_CfZQ1jW9;
  ControlSlice cSlice_39SVSkWK;
  ControlVar cVar_skFXrjYZ;
  ControlBinop cBinop_W40vjxgb;
  ControlBinop cBinop_8Jmp4C83;
  SignalVarf sVarf_C8IKCQJI;
  SignalVarf sVarf_WSsuG5lp;
  SignalVarf sVarf_jQdAez40;
  ControlDelay cDelay_KoBxyLN5;
  ControlDelay cDelay_til7LQfc;
  ControlBinop cBinop_XT6DHUsp;
  ControlBinop cBinop_CSYHZEk5;
  HvTable hTable_SeBwXseX;
  ControlPack cPack_KRLz9hP2;
  ControlBinop cBinop_HIk0jG4X;
  ControlBinop cBinop_Abp6iKPP;
  ControlBinop cBinop_i3T4hqzB;
  ControlBinop cBinop_ZGMplFY2;
  ControlVar cVar_R6dqWvhe;
  ControlVar cVar_HAfEQg8P;
  ControlBinop cBinop_C4SUUbdD;
  ControlBinop cBinop_zyulCZP2;
  ControlBinop cBinop_jEicegz4;
  ControlBinop cBinop_ylQFSHYR;
  ControlBinop cBinop_GanTOILO;
  ControlBinop cBinop_AzSrXSrq;
  ControlBinop cBinop_VuMsrcA5;
  ControlBinop cBinop_g0EtWsUH;
  ControlBinop cBinop_0DG6rk5y;
  ControlBinop cBinop_NWxSBeQq;
  ControlBinop cBinop_bEnZlfzy;
  ControlVar cVar_NYD5Tt1S;
  ControlBinop cBinop_0c4OgTVH;
  ControlBinop cBinop_KQlp34Qe;
  ControlBinop cBinop_HoPOFgk0;
  ControlBinop cBinop_YyAoYgTN;
  ControlBinop cBinop_iFRPIAD1;
  ControlBinop cBinop_rTmjrMtV;
  ControlBinop cBinop_rRAD2XRm;
  ControlBinop cBinop_vi4NvLOA;
  ControlBinop cBinop_he8GwGPJ;
  ControlBinop cBinop_yARal7qO;
  ControlVar cVar_pT3QNNDM;
  ControlVar cVar_BBP5qm9p;
  ControlVar cVar_ZZeKFh3n;
  ControlVar cVar_5ID8RKb2;
  ControlVar cVar_ZmixOlin;
  ControlVar cVar_Tau8vPdr;
  ControlVar cVar_72Lxq37S;
  SignalVarf sVarf_BIwUUTci;
  ControlBinop cBinop_7KJg7Hov;
  ControlVar cVar_6ft77wPK;
  ControlVar cVar_QVSg9Vd1;
  ControlVar cVar_XG0qb4u1;
  ControlVar cVar_pDnLTR0C;
  ControlVar cVar_K1FLPi3P;
  ControlVar cVar_isIzhI8V;
  ControlVar cVar_v2jJclJJ;
  ControlBinop cBinop_NHwJKGKN;
  ControlBinop cBinop_46oQit7t;
  ControlBinop cBinop_J9cYiiZm;
  ControlBinop cBinop_y8jGYTkk;
  SignalVarf sVarf_M11t22Ja;
  SignalVarf sVarf_Mb14oVwb;
};

#endif // _HEAVY_CONTEXT_SIMPLE_OSC_HPP_
