/** "ogsus" */

#ifndef _HEAVY_CONTEXT_SIMPLE_OSC_HPP_
#define _HEAVY_CONTEXT_SIMPLE_OSC_HPP_

// object includes
#include "HeavyContext.hpp"
#include "HvTable.h"
#include "HvControlDelay.h"
#include "HvSignalRPole.h"
#include "HvControlUnop.h"
#include "HvSignalLine.h"
#include "HvControlTabhead.h"
#include "HvSignalTabwrite.h"
#include "HvMath.h"
#include "HvControlCast.h"
#include "HvControlPack.h"
#include "HvSignalDel1.h"
#include "HvSignalBiquad.h"
#include "HvSignalVar.h"
#include "HvControlSystem.h"
#include "HvControlSlice.h"
#include "HvControlBinop.h"
#include "HvControlIf.h"
#include "HvControlVar.h"
#include "HvSignalTabread.h"
#include "HvSignalPhasor.h"

class Heavy_Simple_OSC : public HeavyContext {

 public:
  Heavy_Simple_OSC(double sampleRate, int poolKb=10, int inQueueKb=2, int outQueueKb=0);
  ~Heavy_Simple_OSC();

  const char *getName() override { return "Simple_OSC"; }
  int getNumInputChannels() override { return 0; }
  int getNumOutputChannels() override { return 2; }

  int process(float **inputBuffers, float **outputBuffer, int n) override;
  int processInline(float *inputBuffers, float *outputBuffer, int n) override;
  int processInlineInterleaved(float *inputBuffers, float *outputBuffer, int n) override;

  int getParameterInfo(int index, HvParameterInfo *info) override;
  struct Parameter {
    struct In {
      enum ParameterIn : hv_uint32_t {
        PITCH = 0x94DB5AB5, // Pitch
        REVFEEDBACK = 0xB3A0D463, // RevFeedback
        REVGAIN = 0x3B2EB6DE, // RevGain
        REVPREDELAY = 0x30ADF4D0, // RevPredelay
        VOLUME = 0x528845DB, // Volume
      };
    };
  };

 private:
  HvTable *getTableForHash(hv_uint32_t tableHash) override;
  void scheduleMessageForReceiver(hv_uint32_t receiverHash, HvMessage *m) override;

  // static sendMessage functions
  static void cBinop_I8DWEYHN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rZF2JPD1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_SXKgfTJh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Yg1U1ohz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Tovu3K0K_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_tAG0IBBE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_v7gMdnGa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_UvlQQzUE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_0FpwfvEi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_A8Een5B3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_kUrNi2Zn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_s1leXmd3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_QpumrGWW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_FISsFIlL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_YFRKIybG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_wLPUGwmi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_q9EULU79_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_teG5zUbX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_i8G1a2eT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_brzowTEo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_VRfCekFo_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_21NtdgOz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_sv4hxbc3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_lMilj39S_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_93X2gKqy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_cU0baC5Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_z4kBvAoy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gYm3QNxF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_vmxzlSeG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_P4jF5y2L_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_4adVX0Xu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ScUUe56h_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QtJoQYLf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_eDIjshOS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_vgTo1x8d_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_uv8bWjLc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_nucL0dac_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_36wxCXd0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_LxkdNCZz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_23dGIjfy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_UrdAmnQy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kuVLAtts_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4Yvc1OQJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_HCfeIA7c_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_YDghDgBb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_4i5iHU9w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Ijt7IaaD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_G14PJwAi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_7lRjJgU5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_aqC5dg5q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_lqfJ4Fwu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WIQstErM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Jch8v8EG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KdY6r6sr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ButBcLl6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JEZ5lYT9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_48lZtF12_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_E781S1jL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZE6DKUKa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_at3CSqCu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_E31hpAH9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_AjHMPb9M_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_PCx8Sehx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_Uv7NXPem_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_9jafpizZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_mVDTwY48_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2dYCtl03_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_y3GJfJOn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_1xZ7aGL7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_YPipanZA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_pP0oX8P7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_3yoFzh3N_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_DGWepQc5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xLQjRLC2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Ur9uC08A_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_hesNuNx6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5n5T4nQH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_aOJ1Rfye_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_uWCI9hVj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_buHKK8sP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_4xbbS84R_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ITvd5ylh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_VZ3eaK4f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_ZCNqKPg5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_pf7ShhAr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_gKfXhwO0_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_BRJoY6ZH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_eR5Qjd3P_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_dNjMxoKB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QdSQ5QEG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_KhHpQAcN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_6hs6QnDS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_CDXOFQ5d_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_qHpRdZio_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_c4eEzUJ4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_MCmiXY1x_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_FBwjyubB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tYeDfy7W_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_cJ6oCRSU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_IrgOz7Rb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_t10ItpVU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ETdF9jys_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_pWqmK4GW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_XBMuQmyI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_682m06X5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_3n70rpFZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_dRfWfa4Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_G0BIpOXK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_PtQlgqSc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_8aEa2lMo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ikSTpX6b_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_lqYDu3kO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jZ3GQbWB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6mWqh46Z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_PiHXaOHZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_IKN2yk3i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Eosg4qgv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_f9wWhYJm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_OqZsnrvF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_dqMk7Kb4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_f4pFO7x8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_EpOuMApb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_iN7edz9F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_jua9rYcc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4lBuQaJl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GBQ03HO5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_4pqOFV92_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_zU3CUK1e_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_ndk0w9zl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_6nqE3d7Z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_CO19koIT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Y83SsaIQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_21QcX2xy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gS2yoN7p_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_IL5SZZSx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_1NzYiAjE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZUHJjmUL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_j7Tw6FcJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_55hTvEFz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_7pa4mqpr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_sgPdIe2H_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_a24ZVaCp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_sF2BgZmF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_9MVPMxYe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_m4KPgswP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_WBwIQGaI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_QGg7C5kk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_kRzNmjaN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_8TrVWFVy_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_76U5jyCg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_aGgCWjRO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_b1G5dlPQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4fgMLtPR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_gbOCfDpm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_QWkBPRxt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_wJbgQx6G_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_zRIrb6Jb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_xhzsqxv8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_BKwrhOQA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_7WV7JuE4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_82owZytz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_nPya1Zbu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_HnmFhQPo_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_jGcuu3M4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_s1cnVc8o_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RygbZHBh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MY0V3qlL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Q8OVosbq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_5vkjnlPG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_cIcIPsRf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_42jyV7CM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_7KR7mUKQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_o3CmtgCT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_GNW5K42K_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_tLYwYzuP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_pEK2cL9w_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_CXRcgJtA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_fkCyJrGM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QbZ3AQwF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CVsxU1Vq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_rj6OnhHE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_BvXigcPj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_OQjgCCiO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_EEXRL6sY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_85I1a2Sp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_wQradkJM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_SoqMnkjs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_FWB604e1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_Qv3nZexf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_LBWiIsxo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_4ZzxNIao_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_abYqOpAS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_vkWj3Ixz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ABvLg5RZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_sDDBanNH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_yDHeY8CU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_agVbARoI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_2LlYXDhK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LMR739CO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_jPxgF1Kc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_wll6oROZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_H2IfFsBT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_sAWNrrCy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2mdZKJJp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_tI4MFqfA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_QoMM6tLX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_gsqevfk6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_i4LXdtzU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_O6LeiQYq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_uga0ojk6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_d5XQvj99_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_CnfvoO31_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_aIzUB5fl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Bs8iCsZj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_EzyL4piX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gppfOnFS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kLHmKf9H_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GZgWSbML_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_nk8NthdM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_HDlcRQrY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_dZ1taEJR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_m0MDuUYe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_49ktt3u4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_RbsWjEj9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_ueZ8hjam_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_FVq0cHgt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_7ae6WT0f_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_Z4zYSVCe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_KWPy9bJ6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Zaw2pGku_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_DNnP6WM3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_pHJELsxe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_cdu6BqzJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_o653UKHA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ZKofEVEt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_yFl2IOtK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_9VYJEUHQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_CzTFRbDU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_HZAqu8Ul_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_gzD2KZp3_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_aHfYvrZn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_Yo6icbzn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_fyeDfQoQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_h7lXydkl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Fc9S15BZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ahAuBH7V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_mKS2uiX0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_YsTW3ARx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_RO97xsqN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_1zbrX8lw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_mgKUNNvu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_7EdI9O7T_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_EGTKdSEC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_ybvW8YS5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_oVb07qDv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_G1hkdePX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_XCXecrwc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_B9w09NBJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_cV26Yu4R_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7swKlITw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rXZFvRwF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_58MTqFzK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xP1UUUw1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_5XbPipyH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_fuBJ9j2u_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_9rRpoKFu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_7q7sTcuS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_nrXG1Kwr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ZQLSBHmg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_NMev6sme_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_CYcobl01_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_wB7rAnYG_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_iOLlK5kq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_ZzWEoOEv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Ny1fKtl2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_VWSFiRqp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_PWqKGEmS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_bsXnHI4r_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_4ikZorfq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_s56cRx2n_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_W0LQrZM7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_nCNY8faJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_xmNWdM9S_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_0mn3xhAf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_pUQtyXyC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_V3LPrPel_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_3Bib75vr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_F9NwKrgF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_hxzHmkV5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CBVvA5vi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_iIJ68HCL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6z1e1p1v_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_l3a96YU5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_DGWWs5Jz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GvLTgYTd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_aNNQXAd4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_CTMd2HPz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_PQmX9DkL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_1AbxKDDK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5jpuX0LF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_eLcLZ3iL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_fC1fJ4TM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_cJWoSs40_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_T0zFnfyF_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_tXBJot8W_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_UdhMhxCS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_yFuM59Ke_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_2jlRfMBi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_E9QVw0hi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_SzQOuZJA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_rHij4ODo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_P6MeAdNQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_CcxOIKbr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_tiqnEyT7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_tyf1ZTY7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_p9dqELjh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_pxb3aKdC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_OiYPPgVQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_AOZ7W5JW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Y35G74gi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_m4fycS2f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_08PMgoX1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zhgSH85F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_wzSu6fol_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nAyMaQtI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TpVvDWwW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_oo2CXQxA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_JYg1DlZb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_YWcl6Pfw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_5hTJNFYr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_HieEcCdw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_MLgORMGL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_BQWebaLG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_8mPiUkM6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_LNvVnKns_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_ySUZDvWF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_Z9wXY6TU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_VtODd3Mt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Jdfy9G90_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_tKYHm9eQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TDuZENmC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rxYjzl6q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ch9D8fPt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BwBAlmoW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rMj5h0Lf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Mmiv8o4E_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ylbHDf8c_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_qsEt4WPH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_baeeEd27_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_z2b6Sm7a_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ZiShgIZq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_FWmMRQqf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_7hGXoks5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_09sLZgbN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_BeA64Gpu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_2MorjTx5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tLOhlRAF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_0QQ0HeEe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_DNiBoomV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_aI8xJ5L6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4PeHVtYi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_lFZ1Y4qq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_IQ1K1GfF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_UVJA8oc9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_Vwhof8BK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_ybcQuAtv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_0M64l0Gh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_clKMcG1X_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_TtMEGLm8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_77G3puPH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_AiJ5Xr3E_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_UAouUH8d_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QWdrbhyW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7bxetEsU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8cvU7gH3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_pINQpEzR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kOZTgyly_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_cJwo32Dw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_TZY9t5aJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_1F62o7iI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_WnnZvfhF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_YjLKj9a4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Iy1poKSz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_dR8vtTDI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_WtomsTUw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_Y6HytiLU_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_Lc3XNgRa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_jLtbqstl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WjKk0hdr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mWlPaXr1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ygit6nyt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_fXgesLpe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_HfhajE2l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_T36HUz5G_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_8k7IbRg6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_sycW8HB9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_g8Gc8wfi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_tB5u7Nme_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_f6kMQ1U8_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_AEOTTskN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_2JAThU2d_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Z3p0yQkK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BnUsZKMW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Uw5Q4rsa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_12bc7Sk4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_VYoFQDQV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_bdrRbPtw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_4ervBnrt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2eNyhO2n_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_sUSuTsvw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0Kkb30um_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WZJtsUE0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_sbi2LbHv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_iIUzv7go_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_FhA2GGvp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_kCgBdXfc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_cjCFXVAz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ePQf5vBL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_DNTITy0N_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LXEBB9yE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_EkhEOgEg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_JHtfM96w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_76WkuqSG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_mb5Ix3QR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZAxJfDZo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_AiojmViz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_sBRfvTQU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zEQcWcYu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_wNKKWRKe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_5qZ8VvZR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_IViOngY4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Oqh0GlJ1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_8cPBoDHm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_K2PnY8Nu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LeaTu6EJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_BYOHDWhm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_LCfjIgvk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QhoTeVFq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jPWJcp64_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_GT3xRFtt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_m3Hjlh6x_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_HXFmKHgN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_dtO0LWkW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_lWAdKa0h_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cTabhead_NE3H1yLp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void sTabread_GUgdDAHZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_W84iPXbj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_BFWqdNSG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_4egy1hgc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TzCAJ0Xb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KhWuJiWz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_wTgPd93k_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nKE2XDNH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_oqH6Q3am_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_PnOgdPHC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ZZi1QwKW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_cU49PmFW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_TriIo9CI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_ey4HHz6g_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_JPO8eqRN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_yJW7dWi9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cPack_e58mGv7O_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cPack_z9rkRtZV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cPack_ZHaYA2Pt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Ra55lS1o_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_cG0zulqx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RmdNGInb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ian1Vnis_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_PnzIK3Vh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_Lrtu7Bfa_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_vK7EHZfi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_0haNe4d1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_0vIarOiu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_YQEAdXTa_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_04ljyhD8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_jVsxsyRt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_DfLBRuqL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_UWPxqu2P_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_18z3q9MT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_s3smdupv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ftMlP82l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Mz3Cn5fZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_2t0x4rTx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_avFOEQ0W_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Gm2V1BCF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_fD4XIdUZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_8xmEEMCe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_m29MOnkW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_uvXzTYEC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_EPABsnfY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_AKRoQHV7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_hqXHY4BI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MBPHWxRB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mI9C1uh3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_L9o6iDAh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_bBl7sY27_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_YRqJSNkM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_A9FJrmgD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_VegDv4tJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_F8z8r3Lw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_M3RKnWRO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0LGqexJb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_1U6Yx6bs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KPEo6d3C_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_7vyFm8jN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_acaa0ycT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rhUgudNa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_A3j3O3Cl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_D1vcdQlh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_SyS7fg5X_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_YjwzHzqH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_wvbFaFDq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_qikN6K9Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_pKOlVOEo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_LDO0eJA7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MNh4Kn9o_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_SnyiZ520_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5zh7ZkAQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_eyXtf3Xo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZngYq1Sd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lJak4BQ0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_uOtIDtOv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RI8ghNQA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GcHHqJ2k_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_VFL6tS7j_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_6DsL9it5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_JpAZUyCr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_1vf1wEw1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_FukZHXPY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_nEYxnoII_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_1jfSvbee_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_6edAzdgT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dVdAtccH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_hexYyuQL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_lQ11Ml6B_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_fcBWwRVl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_wjAWZCYd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_XLx9WeAL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_HHEUZn9Z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_DiQyGEIA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_AeCnf3mm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_q52UBONe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_U26oFoqV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Gq1G08Ec_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_7kziUhD7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_gCKwDiqz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_wma42b5t_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_AbjSKJYj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_lU1UErqX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_TDMRWSfy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_Pdo0CRbG_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_z686CO7V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_IYsGG2ao_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_IqHMTtt0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_V0z5ygjq_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_w9S7Hnu8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_2kcl24WN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_WS8t6Yxf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_uKqo1pSQ_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_SQZLsJxL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_cRFJ2GOT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_moxLieAH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4gCekKgo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rHbdj12z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WwV1f1IZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GwINVR8F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_BmWB6Bjf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_R6tHQu0O_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5BcPE5IP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_hs0GPSvX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5nr8FAMt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_xuDugMBa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_3n9DfMMv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_VED1itSd_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_eXx0eoUY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_u9RxI04V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_udDSErTb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_elBR7DSM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_b4dtZHDG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_MyUFhWg7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_TuBilrfj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_5IX3bjVs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void hTable_mtsEGrXy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ygQBiJeC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cPack_z5EiD2v3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GAebJ98X_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Ffn0pfyW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_eJ2UQe0V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_U9yv6x1O_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_FZ4VxKQl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_sFGf5u0K_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TdMOpqqe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_e3dDpana_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_QJoU1Mnj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_NnplWxxS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_cexWYVTa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_eoyV8icy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_harqdADj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_omY9jnBt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ambKQVGE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_XpeOlGgQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_IYyE9Fj3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Exg8a6hm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_esZXHvah_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_pMoYrQtX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_rDHW6peH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_TVqPCFq4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_TSXZmKCS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hk0SwLld_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_OAy9DkIw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_zm7vvp0k_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_qN8uNhoJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_ak5HVysJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_XJObAyhw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_JlmTblPB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_x1iXSGdK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_Wb2oKNSD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_JeiqLHNh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_81T6ZpZ3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_bvH9unRn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_klHIoybS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_oJMIdmZL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_ysiWZTk1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_3868GZ3a_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_6UFQH0NZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_5Q5tuoK1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_BFdOhmj1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_FdEBmVOW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_qi4iGQuv_sendMessage(HeavyContextInterface *, int, const HvMessage *);

  // objects
  SignalPhasor sPhasor_3UbglrGk;
  SignalTabwrite sTabwrite_gJOxRaHk;
  SignalTabhead sTabhead_hf45194G;
  SignalTabread sTabread_cbnNnY2A;
  SignalTabread sTabread_oawe0sKU;
  SignalLine sLine_ximdfCsn;
  SignalLine sLine_bOPyOqOi;
  SignalLine sLine_xh6s3bgg;
  SignalLine sLine_AFkVUVGX;
  SignalLine sLine_TPnjeRBY;
  SignalBiquad sBiquad_s_VwmDq9oE;
  SignalLine sLine_cVolwABw;
  SignalLine sLine_Nhh5ktkA;
  SignalLine sLine_s2RdfzU1;
  SignalLine sLine_c1ElMQrr;
  SignalLine sLine_6AYTH2jr;
  SignalBiquad sBiquad_s_uqelgQkJ;
  SignalTabread sTabread_PtQlgqSc;
  SignalRPole sRPole_WEcG9Dbn;
  SignalLine sLine_67rzUGFA;
  SignalLine sLine_kJUGgjqH;
  SignalTabread sTabread_Z9wXY6TU;
  SignalTabwrite sTabwrite_fo0dfklk;
  SignalTabwrite sTabwrite_3k0Anbcp;
  SignalTabread sTabread_ybvW8YS5;
  SignalTabread sTabread_LBWiIsxo;
  SignalTabread sTabread_V3LPrPel;
  SignalTabread sTabread_O6LeiQYq;
  SignalTabwrite sTabwrite_PhdFRxQK;
  SignalTabwrite sTabwrite_Jdy5LpP0;
  SignalTabwrite sTabwrite_6IvwHegS;
  SignalTabwrite sTabwrite_V8TfAcc1;
  SignalTabread sTabread_OiYPPgVQ;
  SignalTabread sTabread_clKMcG1X;
  SignalRPole sRPole_QKG0esPk;
  SignalTabread sTabread_GUgdDAHZ;
  SignalRPole sRPole_yNJBHYOy;
  SignalTabread sTabread_6nqE3d7Z;
  SignalRPole sRPole_RnYCgH3N;
  SignalTabwrite sTabwrite_zvjQy8mE;
  SignalTabwrite sTabwrite_YjskzF40;
  SignalTabwrite sTabwrite_K5BFI8Sf;
  SignalTabwrite sTabwrite_s6I7gdUd;
  SignalLine sLine_frWm1yVt;
  SignalLine sLine_dJnJF738;
  ControlBinop cBinop_I8DWEYHN;
  ControlBinop cBinop_rZF2JPD1;
  ControlBinop cBinop_SXKgfTJh;
  ControlBinop cBinop_Tovu3K0K;
  ControlVar cVar_tAG0IBBE;
  ControlVar cVar_v7gMdnGa;
  ControlVar cVar_UvlQQzUE;
  ControlVar cVar_0FpwfvEi;
  ControlVar cVar_A8Een5B3;
  ControlVar cVar_kUrNi2Zn;
  ControlVar cVar_s1leXmd3;
  ControlVar cVar_QpumrGWW;
  ControlVar cVar_FISsFIlL;
  ControlVar cVar_YFRKIybG;
  ControlVar cVar_wLPUGwmi;
  ControlVar cVar_q9EULU79;
  ControlVar cVar_teG5zUbX;
  ControlVar cVar_i8G1a2eT;
  ControlVar cVar_brzowTEo;
  ControlSlice cSlice_21NtdgOz;
  ControlBinop cBinop_z4kBvAoy;
  ControlBinop cBinop_gYm3QNxF;
  ControlBinop cBinop_vmxzlSeG;
  ControlVar cVar_ScUUe56h;
  ControlBinop cBinop_QtJoQYLf;
  ControlBinop cBinop_eDIjshOS;
  ControlBinop cBinop_vgTo1x8d;
  ControlBinop cBinop_uv8bWjLc;
  ControlBinop cBinop_36wxCXd0;
  ControlVar cVar_23dGIjfy;
  ControlBinop cBinop_UrdAmnQy;
  ControlBinop cBinop_kuVLAtts;
  ControlBinop cBinop_4Yvc1OQJ;
  ControlBinop cBinop_HCfeIA7c;
  ControlVar cVar_Ijt7IaaD;
  ControlBinop cBinop_G14PJwAi;
  ControlBinop cBinop_aqC5dg5q;
  ControlBinop cBinop_WIQstErM;
  ControlBinop cBinop_Jch8v8EG;
  ControlBinop cBinop_KdY6r6sr;
  ControlBinop cBinop_ButBcLl6;
  ControlBinop cBinop_JEZ5lYT9;
  ControlBinop cBinop_48lZtF12;
  ControlBinop cBinop_E781S1jL;
  ControlBinop cBinop_ZE6DKUKa;
  ControlBinop cBinop_at3CSqCu;
  ControlBinop cBinop_E31hpAH9;
  ControlDelay cDelay_ZCNqKPg5;
  ControlDelay cDelay_pf7ShhAr;
  ControlBinop cBinop_dNjMxoKB;
  ControlBinop cBinop_QdSQ5QEG;
  HvTable hTable_c4eEzUJ4;
  ControlBinop cBinop_FBwjyubB;
  ControlBinop cBinop_tYeDfy7W;
  ControlBinop cBinop_t10ItpVU;
  ControlBinop cBinop_ETdF9jys;
  SignalVarf sVarf_WDfLwx60;
  ControlVar cVar_XBMuQmyI;
  ControlBinop cBinop_682m06X5;
  SignalVarf sVarf_c105d2MA;
  ControlDelay cDelay_3n70rpFZ;
  ControlDelay cDelay_dRfWfa4Q;
  ControlTabhead cTabhead_G0BIpOXK;
  ControlVar cVar_8aEa2lMo;
  ControlBinop cBinop_jZ3GQbWB;
  ControlBinop cBinop_6mWqh46Z;
  ControlBinop cBinop_PiHXaOHZ;
  ControlBinop cBinop_IKN2yk3i;
  ControlBinop cBinop_Eosg4qgv;
  ControlBinop cBinop_f9wWhYJm;
  ControlBinop cBinop_4lBuQaJl;
  ControlBinop cBinop_GBQ03HO5;
  ControlDelay cDelay_4pqOFV92;
  ControlDelay cDelay_zU3CUK1e;
  ControlTabhead cTabhead_ndk0w9zl;
  ControlVar cVar_CO19koIT;
  ControlBinop cBinop_gS2yoN7p;
  ControlBinop cBinop_IL5SZZSx;
  ControlBinop cBinop_1NzYiAjE;
  ControlBinop cBinop_ZUHJjmUL;
  ControlBinop cBinop_j7Tw6FcJ;
  ControlBinop cBinop_55hTvEFz;
  ControlVar cVar_WBwIQGaI;
  ControlDelay cDelay_QGg7C5kk;
  ControlDelay cDelay_kRzNmjaN;
  ControlBinop cBinop_b1G5dlPQ;
  ControlBinop cBinop_4fgMLtPR;
  HvTable hTable_xhzsqxv8;
  ControlVar cVar_7WV7JuE4;
  ControlDelay cDelay_82owZytz;
  ControlDelay cDelay_nPya1Zbu;
  ControlBinop cBinop_RygbZHBh;
  ControlBinop cBinop_MY0V3qlL;
  HvTable hTable_7KR7mUKQ;
  ControlDelay cDelay_GNW5K42K;
  ControlDelay cDelay_tLYwYzuP;
  ControlBinop cBinop_QbZ3AQwF;
  ControlBinop cBinop_CVsxU1Vq;
  HvTable hTable_85I1a2Sp;
  ControlDelay cDelay_SoqMnkjs;
  ControlDelay cDelay_FWB604e1;
  ControlTabhead cTabhead_Qv3nZexf;
  ControlVar cVar_4ZzxNIao;
  ControlBinop cBinop_ABvLg5RZ;
  ControlBinop cBinop_sDDBanNH;
  ControlBinop cBinop_yDHeY8CU;
  ControlBinop cBinop_agVbARoI;
  ControlBinop cBinop_2LlYXDhK;
  ControlBinop cBinop_LMR739CO;
  ControlDelay cDelay_QoMM6tLX;
  ControlDelay cDelay_gsqevfk6;
  ControlTabhead cTabhead_i4LXdtzU;
  ControlVar cVar_uga0ojk6;
  ControlBinop cBinop_aIzUB5fl;
  ControlBinop cBinop_Bs8iCsZj;
  ControlBinop cBinop_EzyL4piX;
  ControlBinop cBinop_gppfOnFS;
  ControlBinop cBinop_kLHmKf9H;
  ControlBinop cBinop_GZgWSbML;
  ControlDelay cDelay_ueZ8hjam;
  ControlDelay cDelay_FVq0cHgt;
  ControlBinop cBinop_Zaw2pGku;
  ControlBinop cBinop_DNnP6WM3;
  HvTable hTable_yFl2IOtK;
  ControlDelay cDelay_CzTFRbDU;
  ControlDelay cDelay_HZAqu8Ul;
  ControlBinop cBinop_fyeDfQoQ;
  ControlBinop cBinop_h7lXydkl;
  HvTable hTable_RO97xsqN;
  ControlDelay cDelay_mgKUNNvu;
  ControlDelay cDelay_7EdI9O7T;
  ControlTabhead cTabhead_EGTKdSEC;
  ControlVar cVar_oVb07qDv;
  ControlBinop cBinop_B9w09NBJ;
  ControlBinop cBinop_cV26Yu4R;
  ControlBinop cBinop_7swKlITw;
  ControlBinop cBinop_rXZFvRwF;
  ControlBinop cBinop_58MTqFzK;
  ControlBinop cBinop_xP1UUUw1;
  ControlDelay cDelay_NMev6sme;
  ControlDelay cDelay_CYcobl01;
  ControlBinop cBinop_Ny1fKtl2;
  ControlBinop cBinop_VWSFiRqp;
  HvTable hTable_W0LQrZM7;
  ControlDelay cDelay_xmNWdM9S;
  ControlDelay cDelay_0mn3xhAf;
  ControlTabhead cTabhead_pUQtyXyC;
  ControlVar cVar_3Bib75vr;
  ControlBinop cBinop_CBVvA5vi;
  ControlBinop cBinop_iIJ68HCL;
  ControlBinop cBinop_6z1e1p1v;
  ControlBinop cBinop_l3a96YU5;
  ControlBinop cBinop_DGWWs5Jz;
  ControlBinop cBinop_GvLTgYTd;
  ControlDelay cDelay_fC1fJ4TM;
  ControlDelay cDelay_cJWoSs40;
  ControlBinop cBinop_yFuM59Ke;
  ControlBinop cBinop_2jlRfMBi;
  HvTable hTable_CcxOIKbr;
  ControlDelay cDelay_tyf1ZTY7;
  ControlDelay cDelay_p9dqELjh;
  ControlTabhead cTabhead_pxb3aKdC;
  ControlVar cVar_AOZ7W5JW;
  ControlBinop cBinop_08PMgoX1;
  ControlBinop cBinop_zhgSH85F;
  ControlBinop cBinop_wzSu6fol;
  ControlBinop cBinop_nAyMaQtI;
  ControlBinop cBinop_TpVvDWwW;
  ControlBinop cBinop_oo2CXQxA;
  ControlDelay cDelay_8mPiUkM6;
  ControlDelay cDelay_LNvVnKns;
  ControlTabhead cTabhead_ySUZDvWF;
  ControlVar cVar_VtODd3Mt;
  ControlBinop cBinop_TDuZENmC;
  ControlBinop cBinop_rxYjzl6q;
  ControlBinop cBinop_ch9D8fPt;
  ControlBinop cBinop_BwBAlmoW;
  ControlBinop cBinop_rMj5h0Lf;
  ControlBinop cBinop_Mmiv8o4E;
  SignalVarf sVarf_eDC0fVso;
  ControlVar cVar_7hGXoks5;
  ControlBinop cBinop_2MorjTx5;
  ControlBinop cBinop_tLOhlRAF;
  ControlBinop cBinop_DNiBoomV;
  ControlBinop cBinop_aI8xJ5L6;
  ControlBinop cBinop_4PeHVtYi;
  SignalVarf sVarf_ZT5GTPzC;
  ControlVar cVar_lFZ1Y4qq;
  ControlIf cIf_IQ1K1GfF;
  ControlBinop cBinop_UVJA8oc9;
  ControlDelay cDelay_Vwhof8BK;
  ControlDelay cDelay_ybcQuAtv;
  ControlTabhead cTabhead_0M64l0Gh;
  ControlVar cVar_TtMEGLm8;
  ControlBinop cBinop_UAouUH8d;
  ControlBinop cBinop_QWdrbhyW;
  ControlBinop cBinop_7bxetEsU;
  ControlBinop cBinop_8cvU7gH3;
  ControlBinop cBinop_pINQpEzR;
  ControlBinop cBinop_kOZTgyly;
  ControlDelay cDelay_dR8vtTDI;
  ControlDelay cDelay_WtomsTUw;
  ControlBinop cBinop_WjKk0hdr;
  ControlBinop cBinop_mWlPaXr1;
  HvTable hTable_8k7IbRg6;
  ControlDelay cDelay_g8Gc8wfi;
  ControlDelay cDelay_tB5u7Nme;
  ControlBinop cBinop_Z3p0yQkK;
  ControlBinop cBinop_BnUsZKMW;
  HvTable hTable_4ervBnrt;
  ControlIf cIf_sUSuTsvw;
  ControlBinop cBinop_0Kkb30um;
  ControlBinop cBinop_WZJtsUE0;
  ControlBinop cBinop_sbi2LbHv;
  ControlBinop cBinop_iIUzv7go;
  ControlBinop cBinop_cjCFXVAz;
  ControlBinop cBinop_LXEBB9yE;
  ControlBinop cBinop_EkhEOgEg;
  ControlVar cVar_JHtfM96w;
  ControlBinop cBinop_ZAxJfDZo;
  ControlBinop cBinop_AiojmViz;
  ControlBinop cBinop_zEQcWcYu;
  ControlBinop cBinop_wNKKWRKe;
  SignalVarf sVarf_o0zDoBJ9;
  ControlVar cVar_5qZ8VvZR;
  ControlBinop cBinop_IViOngY4;
  SignalVarf sVarf_k8tn3zqK;
  ControlVar cVar_Oqh0GlJ1;
  ControlVar cVar_8cPBoDHm;
  ControlBinop cBinop_K2PnY8Nu;
  ControlBinop cBinop_LeaTu6EJ;
  ControlBinop cBinop_QhoTeVFq;
  ControlBinop cBinop_jPWJcp64;
  ControlVar cVar_m3Hjlh6x;
  SignalVarf sVarf_8yY53ufI;
  ControlBinop cBinop_HXFmKHgN;
  SignalVarf sVarf_TtC5BsR1;
  ControlDelay cDelay_dtO0LWkW;
  ControlDelay cDelay_lWAdKa0h;
  ControlTabhead cTabhead_NE3H1yLp;
  ControlVar cVar_W84iPXbj;
  ControlBinop cBinop_TzCAJ0Xb;
  ControlBinop cBinop_KhWuJiWz;
  ControlBinop cBinop_wTgPd93k;
  ControlBinop cBinop_nKE2XDNH;
  ControlBinop cBinop_oqH6Q3am;
  ControlBinop cBinop_PnOgdPHC;
  ControlPack cPack_e58mGv7O;
  ControlPack cPack_z9rkRtZV;
  ControlPack cPack_ZHaYA2Pt;
  ControlBinop cBinop_Ra55lS1o;
  ControlBinop cBinop_cG0zulqx;
  ControlBinop cBinop_RmdNGInb;
  ControlVar cVar_PnzIK3Vh;
  ControlSlice cSlice_vK7EHZfi;
  ControlVar cVar_0vIarOiu;
  ControlSlice cSlice_04ljyhD8;
  ControlVar cVar_DfLBRuqL;
  ControlSlice cSlice_18z3q9MT;
  ControlVar cVar_ftMlP82l;
  ControlBinop cBinop_avFOEQ0W;
  ControlBinop cBinop_Gm2V1BCF;
  SignalVarf sVarf_OXlVbtbQ;
  SignalVarf sVarf_I3FPghgQ;
  SignalVarf sVarf_jWrQS0Ni;
  ControlBinop cBinop_hqXHY4BI;
  ControlBinop cBinop_MBPHWxRB;
  ControlBinop cBinop_mI9C1uh3;
  ControlBinop cBinop_A9FJrmgD;
  ControlBinop cBinop_VegDv4tJ;
  ControlBinop cBinop_F8z8r3Lw;
  ControlBinop cBinop_M3RKnWRO;
  ControlBinop cBinop_0LGqexJb;
  ControlBinop cBinop_1U6Yx6bs;
  ControlBinop cBinop_KPEo6d3C;
  ControlVar cVar_7vyFm8jN;
  ControlBinop cBinop_acaa0ycT;
  ControlBinop cBinop_rhUgudNa;
  ControlBinop cBinop_A3j3O3Cl;
  ControlVar cVar_SyS7fg5X;
  ControlVar cVar_YjwzHzqH;
  ControlBinop cBinop_wvbFaFDq;
  ControlBinop cBinop_qikN6K9Q;
  ControlBinop cBinop_pKOlVOEo;
  ControlBinop cBinop_MNh4Kn9o;
  ControlBinop cBinop_SnyiZ520;
  ControlBinop cBinop_5zh7ZkAQ;
  ControlBinop cBinop_eyXtf3Xo;
  ControlBinop cBinop_ZngYq1Sd;
  ControlBinop cBinop_lJak4BQ0;
  ControlBinop cBinop_uOtIDtOv;
  ControlBinop cBinop_RI8ghNQA;
  ControlBinop cBinop_GcHHqJ2k;
  ControlVar cVar_gCKwDiqz;
  ControlSlice cSlice_AbjSKJYj;
  ControlVar cVar_TDMRWSfy;
  ControlSlice cSlice_z686CO7V;
  ControlVar cVar_IqHMTtt0;
  ControlSlice cSlice_w9S7Hnu8;
  ControlVar cVar_WS8t6Yxf;
  ControlSlice cSlice_SQZLsJxL;
  SignalVarf sVarf_CzLQyl6J;
  ControlIf cIf_moxLieAH;
  ControlBinop cBinop_4gCekKgo;
  ControlBinop cBinop_rHbdj12z;
  ControlBinop cBinop_WwV1f1IZ;
  ControlBinop cBinop_GwINVR8F;
  ControlBinop cBinop_5BcPE5IP;
  ControlDelay cDelay_xuDugMBa;
  ControlDelay cDelay_3n9DfMMv;
  ControlBinop cBinop_udDSErTb;
  ControlBinop cBinop_elBR7DSM;
  HvTable hTable_mtsEGrXy;
  ControlPack cPack_z5EiD2v3;
  ControlBinop cBinop_GAebJ98X;
  ControlVar cVar_Ffn0pfyW;
  ControlVar cVar_eJ2UQe0V;
  SignalVarf sVarf_QunF1xzH;
  ControlVar cVar_U9yv6x1O;
  ControlBinop cBinop_FZ4VxKQl;
  ControlBinop cBinop_sFGf5u0K;
  ControlBinop cBinop_TdMOpqqe;
  ControlBinop cBinop_e3dDpana;
  SignalVarf sVarf_ptMPAl5T;
  SignalVarf sVarf_IW9RoBuM;
};

#endif // _HEAVY_CONTEXT_SIMPLE_OSC_HPP_
